# Generated by Django 6.0.6 on 2026-07-27 04:12

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_remove_phonenumber_unique_primary_phone_per_org_and_more'),
        ('communications', '0002_staticmessagetemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staticmessagetemplate',
            name='unique_static_template',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='handoffevent',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='handoffevent',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='handoffevent',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='outboundmessagequeue',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='outboundmessagequeue',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='outboundmessagequeue',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='handoffevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outboundmessagequeue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staticmessagetemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='staticmessagetemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'user', 'template_type'), name='unique_static_template'),
        ),
        migrations.RemoveField(
            model_name='staticmessagetemplate',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='staticmessagetemplate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='staticmessagetemplate',
            name='metadata',
        ),
    ]
