# Generated by Django 6.0.6 on 2026-07-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_staticmessagetemplate_unique_static_template_and_more'),
    ]

    operations = []
