# Generated by Django 6.0.6 on 2026-07-27 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_twilioconfiguration_event_webhook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioNumberVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='businesstype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='businesstype',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='businesstype',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='freetraildetails',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='freetraildetails',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='freetraildetails',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='freetrailphonenumber',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='freetrailphonenumber',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='twilioconfiguration',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='twilioconfiguration',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='twilioconfiguration',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='freetraildetails',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='freetrailphonenumber',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='industry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twilioconfiguration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
