# Generated by Django 6.0.6 on 2026-07-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_twilionumberverification_remove_apikey_deleted_at_and_more'),
    ]

    operations = []
