# Generated by Django 6.0.6 on 2026-07-27 05:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_businessaddress_id_alter_businesslink_id_and_more'),
        ('core', '0012_alter_apikey_id_alter_auditlog_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFreeTrailNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trail_number', models.CharField(blank=True, max_length=20, null=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('free_trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.freetrailphonenumber')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_phone_numbers', to='business.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FreeTrailDetails',
        ),
    ]
