# Generated by Django 6.0.6 on 2026-07-28 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_provideraccount_user'),
        ('core', '0013_userfreetrailnumber_delete_freetraildetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TollFreeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_profile_sid', models.CharField(max_length=64)),
                ('tollfree_phone_number_sid', models.CharField(max_length=64)),
                ('verification_sid', models.CharField(blank=True, help_text='Twilio TFV SID returned after submission.', max_length=64)),
                ('external_reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(max_length=255)),
                ('doing_business_as', models.CharField(blank=True, max_length=255)),
                ('business_website', models.URLField()),
                ('notification_email', models.EmailField(max_length=254)),
                ('business_registration_number', models.CharField(blank=True, max_length=100)),
                ('business_registration_authority', models.CharField(blank=True, max_length=100)),
                ('business_registration_country', models.CharField(blank=True, max_length=10)),
                ('business_registration_phone_number', models.CharField(blank=True, max_length=30)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('use_case_categories', models.JSONField(default=list)),
                ('use_case_summary', models.TextField()),
                ('production_message_sample', models.TextField()),
                ('message_volume', models.PositiveIntegerField(default=0)),
                ('additional_information', models.TextField(blank=True)),
                ('opt_in_type', models.CharField(choices=[('VERBAL', 'Verbal'), ('WEB_FORM', 'Web Form'), ('PAPER_FORM', 'Paper Form'), ('MOBILE_QR_CODE', 'Mobile QR Code'), ('TEXT', 'Text'), ('IVR', 'IVR'), ('UNKNOWN', 'Unknown')], default='VERBAL', max_length=30)),
                ('opt_in_image_urls', models.JSONField(blank=True, default=list)),
                ('opt_in_confirmation_message', models.TextField(blank=True)),
                ('opt_in_keywords', models.JSONField(blank=True, default=list)),
                ('help_message_sample', models.TextField(blank=True)),
                ('privacy_policy_url', models.URLField(blank=True)),
                ('terms_and_conditions_url', models.URLField(blank=True)),
                ('age_gated_content', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending Review'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='draft', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejection_code', models.CharField(blank=True, max_length=100)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free_trail_phone_number', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tfv_verification', to='core.freetrailphonenumber')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tfv_verifications', to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tfv_verification', to='business.phonenumber')),
            ],
            options={
                'db_table': 'tfv_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TwilioNumberVerification',
        ),
    ]
