# Generated by Django 6.0.6 on 2026-07-28 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_provideraccount_user'),
        ('core', '0014_tollfreeverification_delete_twilionumberverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tollfreeverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tfv_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tollfreeverification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tfv_verifications', to='business.organization'),
        ),
    ]
