# Generated by Django 6.0.6 on 2026-07-28 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_provideraccount_user'),
        ('core', '0015_tollfreeverification_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollfreeverification',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tfv_verifications', to='business.organization'),
        ),
        migrations.AlterField(
            model_name='tollfreeverification',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tfv_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
