# Generated by Django 6.0.6 on 2026-07-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_tollfreeverification_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollfreeverification',
            name='rejection_reasons',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='freetrailphonenumber',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('VERIFICATION PENDING', 'Verification Pending'), ('RELEASED', 'Released'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tollfreeverification',
            name='verification_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending Review'), ('in_review', 'In Review'), ('twilio_approved', 'Twilio Approved'), ('rejected', 'Rejected'), ('rejected_permanent', 'Rejected Permanent'), ('canceled', 'Canceled')], default='draft', max_length=30),
        ),
    ]
