# Generated by Django 6.0.6 on 2026-07-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_freetrailphonenumber_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollfreeverification',
            name='business_type',
            field=models.CharField(blank=True, choices=[('SOLE_PROPRIETOR', 'Sole Proprietor'), ('PARTNERSHIP', 'Partnership'), ('COOPERATIVE', 'Cooperative'), ('NON_PROFIT', 'Non-Profit'), ('PRIVATE_PROFIT', 'Private Profit'), ('PUBLIC_PROFIT', 'Public Profit'), ('GOVERNMENT', 'Government')], max_length=100),
        ),
    ]
