# Generated by Django 6.0.6 on 2026-07-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_tollfreeverification_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetrailphonenumber',
            name='account_sid',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
