# Generated by Django 6.0.6 on 2026-07-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_freetrailphonenumber_account_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetrailphonenumber',
            name='usages_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freetrailphonenumber',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('VERIFICATION REVIEW', 'Verification Review'), ('VERIFICATION PENDING', 'Verification Pending'), ('VERIFICATION REJECTED', 'Verification Rejected'), ('RELEASED', 'Released'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='tollfreeverification',
            name='business_registration_authority',
            field=models.CharField(blank=True, choices=[('EIN', 'Employer Identification Number (EIN)'), ('CBN', 'Company Business Number (CBN)'), ('CRN', 'Company Registration Number (CRN)'), ('PROVINCIAL_NUMBER', 'Provincial Registration Number'), ('VAT', 'VAT Number'), ('ACN', 'Australian Company Number (ACN)'), ('ABN', 'Australian Business Number (ABN)'), ('BRN', 'Business Registration Number (BRN)'), ('SIREN', 'French SIREN'), ('SIRET', 'French SIRET'), ('NZBN', 'New Zealand Business Number (NZBN)'), ('USt-IdNr', 'German VAT ID (USt-IdNr)'), ('CIF', 'Spanish CIF'), ('NIF', 'Spanish NIF'), ('CNPJ', 'Brazilian CNPJ'), ('UID', 'UID'), ('NEQ', 'Quebec Enterprise Number (NEQ)'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tollfreeverification',
            name='business_type',
            field=models.CharField(blank=True, choices=[('PRIVATE_PROFIT', 'Private Profit'), ('PUBLIC_PROFIT', 'Public Profit'), ('SOLE_PROPRIETOR', 'Sole Proprietor'), ('NON_PROFIT', 'Non-Profit'), ('GOVERNMENT', 'Government')], max_length=100),
        ),
    ]
