# Generated by Django 6.0.6 on 2026-07-29 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_freetrailphonenumber_usages_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfreetrailnumber',
            name='organization',
        ),
        migrations.AddField(
            model_name='userfreetrailnumber',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_phone_numbers', to=settings.AUTH_USER_MODEL),
        ),
    ]
