# Generated by Django 6.0.6 on 2026-08-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_userfreetrailnumber_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfreetrailnumber',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
