# Generated by Django 6.0.6 on 2026-08-08 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_localverification_messaging_service_attachment_sid'),
        ('core', '0025_a2pbrand_a2pcampaign_messagingservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_sid', models.CharField(max_length=64, unique=True)),
                ('policy_sid', models.CharField(blank=True, max_length=64)),
                ('friendly_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='business.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
