# Generated by Django 6.0.6 on 2026-08-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_customerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessagingService',
        ),
    ]
