# Generated by Django 6.0.6 on 2026-08-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_delete_messagingservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a2pcampaign',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='a2pcampaign',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='organization',
        ),
        migrations.DeleteModel(
            name='A2PBrand',
        ),
        migrations.DeleteModel(
            name='A2PCampaign',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
