# Generated by Django 6.0.6 on 2026-07-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_remove_purchaseinfo_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_type',
            field=models.CharField(choices=[('day', 'Day'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free_trial', 'Free Trail'), ('starter', 'Starter'), ('growth', 'Growth'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=20),
        ),
    ]
