# Generated by Django 6.0.6 on 2026-07-27 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_subscriptionplan_billing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='purchaseinfo',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='purchaseinfo',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='metadata',
        ),
    ]
