# Generated by Django 6.0.6 on 2026-07-27 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_businessaddress_id_alter_businesslink_id_and_more'),
        ('subscription', '0009_alter_invoice_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='business.organization'),
        ),
    ]
