# Generated by Django 6.0.6 on 2026-07-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_alter_usersubscription_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='end_date',
        ),
    ]
