# Generated by Django 6.0.6 on 2026-07-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_alter_usersubscription_billing_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free_trial', 'Free Trail'), ('paid', 'Paid')], max_length=20),
        ),
    ]
