# Generated by Django 6.0.6 on 2026-07-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_alter_subscriptionplan_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinfo',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
