# Generated by Django 6.0.6 on 2026-08-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_alter_purchaseinfo_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('awaiting_payment', 'Awaiting Payment'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('close', 'Close')], db_index=True, default='awaiting_payment', max_length=20),
        ),
    ]
