# Generated by Django 6.0.6 on 2026-08-30 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_alter_usersubscription_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='app_bundle_id',
            field=models.CharField(default='com.chesera.app', max_length=100),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='currency_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='expiry_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_subscription_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='medium',
            field=models.CharField(blank=True, choices=[('apple', 'Apple'), ('google', 'Google')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='original_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='product_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='purchase_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='store_environment',
            field=models.CharField(blank=True, choices=[('production', 'Production'), ('sandbox', 'Sandbox')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='store_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='verification_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscription.subscriptionplan'),
        ),
    ]
