# Generated by Django 6.0.6 on 2026-08-30 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0016_usersubscription_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
