# Generated by Django 6.0.6 on 2026-07-27 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='device',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
