# Generated by Django 6.0.6 on 2026-07-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_device_deleted_at_remove_device_is_deleted_and_more'),
    ]

    operations = []
