# Generated by Django 6.0.6 on 2026-08-30 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0029_delete_businessaddress'),
        ('communications', '0004_alter_aianalysis_id_alter_conversation_id_and_more'),
        ('crm', '0003_alter_followupreminder_id_alter_lead_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentDMProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('processing', 'Processing'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('failed', 'Failed')], db_index=True, default='incomplete', max_length=30)),
                ('phone_number', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('whatsapp_phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('billing_model', models.CharField(blank=True, default='organization', max_length=50)),
                ('inherit_contacts', models.BooleanField(default=False)),
                ('inherit_templates', models.BooleanField(default=False)),
                ('inherit_tcr_brand', models.BooleanField(default=True)),
                ('inherit_tcr_campaign', models.BooleanField(default=True)),
                ('sandbox', models.BooleanField(db_index=True, default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentdm_profile', to='business.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentdm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentDMMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_message_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('channel', models.CharField(choices=[('auto', 'Auto'), ('sms', 'SMS'), ('rcs', 'RCS'), ('whatsapp', 'WhatsApp')], default='auto', max_length=20)),
                ('from_number', models.CharField(blank=True, default='', max_length=30)),
                ('to_number', models.CharField(blank=True, default='', max_length=30)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('sandbox', models.BooleanField(db_index=True, default=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentdm_messages', to='communications.conversation')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentdm_messages', to='crm.lead')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentdm_messages', to='business.organization')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='sentdm.sentdmprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentDMWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('event_type', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('profile_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('signature_verified', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='received', max_length=30)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'status'], name='sentdm_sent_event_t_9bc617_idx'), models.Index(fields=['event_id'], name='sentdm_sent_event_i_e94302_idx'), models.Index(fields=['profile_id'], name='sentdm_sent_profile_645cf1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sentdmprofile',
            index=models.Index(fields=['status', 'sandbox'], name='sentdm_sent_status_bfb62e_idx'),
        ),
        migrations.AddIndex(
            model_name='sentdmprofile',
            index=models.Index(fields=['organization', 'status'], name='sentdm_sent_organiz_4e97a1_idx'),
        ),
        migrations.AddIndex(
            model_name='sentdmmessage',
            index=models.Index(fields=['sent_message_id'], name='sentdm_sent_sent_me_83f6bb_idx'),
        ),
        migrations.AddIndex(
            model_name='sentdmmessage',
            index=models.Index(fields=['direction', 'status'], name='sentdm_sent_directi_a7e9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='sentdmmessage',
            index=models.Index(fields=['organization', 'created_at'], name='sentdm_sent_organiz_5b1e11_idx'),
        ),
    ]
