# Generated by Codex on 2026-08-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0030_organization_sentdm_compliance_fields"),
        ("sentdm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentDMCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign_id", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("campaign_type", models.CharField(blank=True, default="App", max_length=50)),
                ("messaging_use_case_us", models.CharField(blank=True, default="CUSTOMER_CARE", max_length=60)),
                ("volume", models.CharField(blank=True, default="", max_length=20)),
                ("status", models.CharField(choices=[("SENT_CREATED", "Sent Created"), ("ACTIVE", "Active"), ("EXPIRED", "Expired"), ("FAILED", "Failed")], db_index=True, default="SENT_CREATED", max_length=30)),
                ("submitted_to_tcr", models.BooleanField(default=False)),
                ("tcr_campaign_id", models.CharField(blank=True, default="", max_length=120)),
                ("sandbox", models.BooleanField(db_index=True, default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sentdm_campaigns", to="business.organization")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="campaigns", to="sentdm.sentdmprofile")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["profile", "status"], name="sentdm_sent_profile_2eea8d_idx"),
                    models.Index(fields=["organization", "status"], name="sentdm_sent_organiz_3f5744_idx"),
                    models.Index(fields=["campaign_id"], name="sentdm_sent_campaig_a724fe_idx"),
                ],
            },
        ),
    ]