# Generated by Django 6.0.6 on 2026-07-27 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_remove_phonenumber_messaging_service_sid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='phonenumber',
            name='unique_primary_phone_per_org',
        ),
        migrations.RemoveField(
            model_name='businessaddress',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='businessaddress',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='businessaddress',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='businesslink',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='businesslink',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='businesslink',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='businesssetting',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='businesssetting',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='businesssetting',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='provideraccount',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='provideraccount',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='businessaddress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businesslink',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businesssetting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provideraccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('organization', 'is_primary'), name='unique_primary_phone_per_org'),
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='is_deleted',
        ),
    ]
