# Generated by Django 6.0.6 on 2026-07-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_remove_phonenumber_unique_primary_phone_per_org_and_more'),
    ]

    operations = []
