# Generated by Django 6.0.6 on 2026-07-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_alter_phonenumber_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('VERIFICATION PENDING', 'Verification Pending'), ('VERIFICATION REJECTED', 'Verification Rejected'), ('RELEASED', 'Released'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30),
        ),
    ]
