# Generated by Django 6.0.6 on 2026-08-02 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_alter_phonenumber_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_numbers', to='business.provideraccount'),
        ),
    ]
