# Generated by Django 6.0.6 on 2026-08-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_phonenumber_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('MESSAGING_SERVICE', 'Messaging Service'), ('BRAND_SUBMITTED', 'Brand Submitted'), ('BRAND_APPROVED', 'Brand Approved'), ('CAMPAIGN_SUBMITTED', 'Campaign Submitted'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=30)),
                ('complete_progress', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
