# Generated by Django 6.0.6 on 2026-08-03 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_localverification'),
        ('core', '0025_a2pbrand_a2pcampaign_messagingservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='localverification',
            name='a2p_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a2p_brands', to='core.a2pbrand'),
        ),
        migrations.AddField(
            model_name='localverification',
            name='a2p_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a2p_campaigns', to='core.a2pcampaign'),
        ),
        migrations.AddField(
            model_name='localverification',
            name='messaging_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_services', to='core.messagingservice'),
        ),
        migrations.AddField(
            model_name='localverification',
            name='phone_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_model', to='business.phonenumber'),
        ),
    ]
