# Generated by Django 6.0.6 on 2026-08-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_localverification_a2p_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
