# Generated by Django 6.0.6 on 2026-08-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_localverification_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='localverification',
            name='messaging_service_attachment_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
