# Generated by Django 6.0.6 on 2026-08-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_localverification_messaging_service_attachment_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='business_registration_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
