# Generated by Django 6.0.6 on 2026-08-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_organization_business_registration_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaddress',
            name='twilio_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
