# Generated by Django 6.0.6 on 2026-08-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_businessaddress_twilio_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessaddress',
            old_name='address_line_1',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='businessaddress',
            old_name='address_line_2',
            new_name='street_secondary',
        ),
    ]
