# Generated by Django 6.0.6 on 2026-08-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_rename_address_line_1_businessaddress_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaddress',
            name='street_secondary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
