# Generated by Django 6.0.6 on 2026-08-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_alter_businessaddress_street_secondary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalVerification',
        ),
    ]
