# Generated by Django 6.0.6 on 2026-08-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_delete_localverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessAddress',
        ),
    ]
