# Generated by Codex on 2026-08-30

from django.db import migrations, models


def ensure_sentdm_messaging_use_case_us_column(apps, schema_editor):
    table_name = "organizations"
    column_name = "sentdm_messaging_use_case_us"

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if column_name in existing_columns:
        return

    Organization = apps.get_model("business", "Organization")
    field = models.CharField(max_length=60, blank=True, default="CUSTOMER_CARE")
    field.set_attributes_from_name(column_name)
    schema_editor.add_field(Organization, field)


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0030_organization_sentdm_compliance_fields"),
    ]

    operations = [
        migrations.RunPython(ensure_sentdm_messaging_use_case_us_column, migrations.RunPython.noop),
    ]