# Generated by Codex on 2026-08-30

from django.db import migrations


def normalize_sentdm_expected_daily_volume(apps, schema_editor):
    table_name = "organizations"
    column_name = "sentdm_expected_daily_volume"

    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }
        if column_name not in columns:
            return

        cursor.execute(
            """
            UPDATE organizations
            SET sentdm_expected_daily_volume = 0
            WHERE sentdm_expected_daily_volume IS NULL
               OR typeof(sentdm_expected_daily_volume) != 'integer'
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0031_ensure_sentdm_messaging_use_case_us_column"),
    ]

    operations = [
        migrations.RunPython(normalize_sentdm_expected_daily_volume, migrations.RunPython.noop),
    ]
