# Generated by Django 6.0.6 on 2026-07-27 04:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_remove_phonenumber_unique_primary_phone_per_org_and_more'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('note', models.TextField(blank=True)),
                ('is_sent', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'crm_followup_reminders',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='lead',
            name='unique_lead_per_organization',
        ),
        migrations.RemoveConstraint(
            model_name='leadtag',
            name='unique_lead_tag',
        ),
        migrations.RemoveConstraint(
            model_name='leadtagassignment',
            name='unique_tag_assignment',
        ),
        migrations.RemoveField(
            model_name='leadactivity',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='leadactivity',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leadtag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leadtagassignment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('organization', 'contact_number'), name='unique_lead_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='leadtag',
            constraint=models.UniqueConstraint(fields=('lead', 'name'), name='unique_lead_tag'),
        ),
        migrations.AddConstraint(
            model_name='leadtagassignment',
            constraint=models.UniqueConstraint(fields=('lead', 'tag'), name='unique_tag_assignment'),
        ),
        migrations.AddField(
            model_name='followupreminder',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='followupreminder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='business.organization'),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='leadtag',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='leadtag',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='leadtag',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='leadtagassignment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='leadtagassignment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='leadtagassignment',
            name='metadata',
        ),
    ]
