# Generated by Django 6.0.6 on 2026-07-27 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('business', '0013_remove_phonenumber_unique_primary_phone_per_org_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prompttemplate',
            name='unique_prompt_version',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='aimodellog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='aimodellog',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='aimodellog',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='aiusagelog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='aiusagelog',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aimodellog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_prompt_version'),
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='metadata',
        ),
    ]
