# Generated by Django 6.0.6 on 2026-07-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_remove_prompttemplate_unique_prompt_version_and_more'),
    ]

    operations = []
