# Generated by Django 6.0.6 on 2026-08-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localverification',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('MESSAGING_SERVICE', 'Messaging Service'), ('BRAND_SUBMITTED', 'Brand Submitted'), ('BRAND_APPROVED', 'Brand Approved'), ('CAMPAIGN_SUBMITTED', 'Campaign Submitted'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=50),
        ),
    ]
