# Generated by Django 6.0.6 on 2026-08-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0002_alter_localverification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagingservice',
            name='messaging_service_sid',
        ),
    ]
