# Generated by Django 6.0.6 on 2026-08-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0003_remove_messagingservice_messaging_service_sid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessagingServicePhoneAssignment',
        ),
    ]
