# Generated by Django 6.0.6 on 2026-08-11 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_delete_localverification'),
        ('twilio_app', '0005_alter_localverification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaddress',
            name='account_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='a2pbrand',
            name='a2p_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='new_brands', to='twilio_app.a2pprofile'),
        ),
        migrations.AlterField(
            model_name='a2pbrand',
            name='customer_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='new_brands', to='twilio_app.customerprofile'),
        ),
        migrations.AlterField(
            model_name='a2pbrand',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_a2p_brands', to='business.organization'),
        ),
        migrations.AlterField(
            model_name='a2pcampaign',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='new_campaigns', to='twilio_app.a2pbrand'),
        ),
        migrations.AlterField(
            model_name='a2pcampaign',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_a2p_campaigns', to='business.organization'),
        ),
        migrations.AlterField(
            model_name='businessaddress',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_business_addresses', to='business.organization'),
        ),
        migrations.AlterField(
            model_name='businessenduser',
            name='customer_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_end_users', to='twilio_app.customerprofile'),
        ),
        migrations.AlterField(
            model_name='businessenduser',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_business_end_users', to='business.organization'),
        ),
        migrations.AlterField(
            model_name='trusthubentityassignment',
            name='customer_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_entity_assignments', to='twilio_app.customerprofile'),
        ),
        migrations.AlterField(
            model_name='trusthubevaluation',
            name='a2p_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_evaluations', to='twilio_app.a2pprofile'),
        ),
        migrations.AlterField(
            model_name='trusthubevaluation',
            name='customer_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_evaluations', to='twilio_app.customerprofile'),
        ),
    ]
