# Generated by Django 6.0.6 on 2026-08-11 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_delete_localverification'),
        ('twilio_app', '0006_businessaddress_account_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessenduser',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_end_users', to='business.organization'),
        ),
    ]
