# Generated by Django 6.0.6 on 2026-08-11 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_delete_businessaddress'),
        ('twilio_app', '0007_alter_businessenduser_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaddress',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_addresses', to='business.organization'),
        ),
    ]
