# Generated by Django 6.0.6 on 2026-08-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0008_alter_businessaddress_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaddress',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
