# Generated by Django 6.0.6 on 2026-08-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0009_alter_businessaddress_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaddress',
            name='friendly_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessaddress',
            name='street_secondary',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessaddress',
            name='twilio_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
