# Generated by Django 6.0.6 on 2026-08-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0010_alter_businessaddress_friendly_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a2pprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='a2pprofile',
            name='failure_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='a2pprofile',
            name='friendly_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='a2pprofile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='a2pprofile',
            name='policy_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
