# Generated by Django 6.0.6 on 2026-08-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0011_alter_a2pprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a2pprofile',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trusthubevaluation',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
