# Generated by Django 6.0.6 on 2026-08-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0013_alter_a2pprofile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a2pbrand',
            name='brand_type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('LOW_VOLUME_STANDARD', 'Low Volume Standard'), ('SOLE_PROPRIETOR', 'Sole Proprietor')], default='STANDARD', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='a2pbrand',
            name='failure_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='a2pbrand',
            name='identity_status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='a2pbrand',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='a2pbrand',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
