# Generated by Django 6.0.6 on 2026-08-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0014_alter_a2pbrand_brand_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='a2pbrand',
            name='brand_feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='a2pbrand',
            name='brand_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='a2pbrand',
            name='government_entity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='a2pbrand',
            name='mock',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='a2pbrand',
            name='russell_3000',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='a2pbrand',
            name='tax_exempt_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='a2pbrand',
            name='tcr_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
