# Generated by Django 6.0.6 on 2026-08-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0015_a2pbrand_brand_feedback_a2pbrand_brand_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localverification',
            name='a2p_brand_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='localverification',
            name='a2p_profile_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='localverification',
            name='address_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='localverification',
            name='customer_profile_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='localverification',
            name='end_user_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='localverification',
            name='profile_evaluation_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='localverification',
            name='trusthub_evaluation_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
