# Generated by Django 6.0.6 on 2026-08-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0016_localverification_a2p_brand_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localverification',
            name='supporting_document_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
