# Generated by Django 6.0.6 on 2026-08-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0017_localverification_supporting_document_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='localverification',
            name='end_user_assign_to_customer_profiles_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
