# Generated by Django 6.0.6 on 2026-08-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0018_localverification_end_user_assign_to_customer_profiles_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='localverification',
            name='phone_number_assign_to_customer_profile_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='localverification',
            name='primary_customer_profile_assign_to_customer_profile_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='localverification',
            name='supporting_document_assign_to_customer_profile_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
