# Generated by Django 6.0.6 on 2026-08-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0022_rename_trusthub_evaluation_sid_localverification_a2p_end_user_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localverification',
            name='a2p_campaign_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
