# Generated by Django 6.0.6 on 2026-08-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0023_localverification_a2p_campaign_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='localverification',
            name='messaging_service_assign_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='localverification',
            name='messaging_service_sid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
